const products: any [] = [
  {category: 'starters', data: {id: 1, name: 'french_fries', price: 30, discount: 0, image: 'french_fries.jpg'}},
  {category: 'starters', data: {id: 2, name: 'bruschetta', price: 25, discount: 0, image: 'bruschetta.jpg'}},
  {category: 'starters', data: {id: 3, name: 'humus', price: 55, discount: 0, image: 'humus.jpg'}},
  {category: 'main_dishes', data: {id: 4, name: 'chicken_steak', price: 85, discount: 0, image: 'chicken_steak.jpg'}},
  {category: 'main_dishes', data: {id: 5, name: 'beef_steak', price: 105, discount: 0, image: 'beef_steak.jpg'}},
  {category: 'main_dishes', data: {id: 6, name: 'hamburger', price: 55, discount: 0, image: 'hamburger.jpg'}},
  {category: 'main_dishes', data: {id: 7, name: 'cheese_burger', price: 55, discount: 0, image: 'cheese_burger.jpg'}},
  {category: 'pizza', data: {id: 8, name: 'quattro_formaggi', price: 155, discount: 0, image: 'quattro_formaggi.jpg'}},
  {category: 'pizza', data: {id: 9, name: 'mozarella', price: 130, discount: 0, image: 'mozarella.jpg'}},
  {category: 'pizza', data: {id: 10, name: 'parmesani', price: 130, discount: 0, image: 'parmesani.jpg'}},
  {category: 'pizza', data: {id: 11, name: 'prosciutto', price: 155, discount: 0, image: 'prosciutto.jpg'}},
  {category: 'deserts', data: {id: 12, name: 'chocolate_cake', price: 80, discount: 0, image: 'cake.jpg'}},
  {category: 'deserts', data: {id: 13, name: 'waffle', price: 70, discount: 0, image: 'waffle.jpg'}},
  {category: 'deserts', data: {id: 14, name: 'pancake', price: 50, discount: 0, image: 'pancake.jpg'}},
  {category: 'deserts', data: {id: 15, name: 'fruit_salad', price: 50, discount: 0, image: 'fruit_salad.jpg'}},
  {category: 'hot_drinks', data: {id: 16, name: 'espresso', price: 40, discount: 0, image: 'espresso.jpg'}},
  {category: 'hot_drinks', data: {id: 17, name: 'americano', price: 40, discount: 0, image: 'americano.jpg'}},
  {category: 'hot_drinks', data: {id: 18, name: 'latte', price: 40, discount: 0, image: 'latte.jpg'}},
  {category: 'hot_drinks', data: {id: 19, name: 'macchiato', price: 40, discount: 0, image: 'macchiato.jpg'}},
  {category: 'hot_drinks', data: {id: 20, name: 'capuccino', price: 40, discount: 0, image: 'capuccino.jpg'}},
  {category: 'hot_drinks', data: {id: 21, name: 'black_tea', price: 20, discount: 0, image: 'black_tea.jpg'}},
  {category: 'hot_drinks', data: {id: 22, name: 'green_tea', price: 20, discount: 0, image: 'green_tea.jpg'}},
  {category: 'beverages', data: {id: 23, name: 'coca_cola', price: 80, discount: 0, image: 'coca_cola.jpg'}},
  {category: 'beverages', data: {id: 24, name: 'fanta', price: 40, discount: 0, image: 'fanta.jpg'}},
  {category: 'beverages', data: {id: 25, name: 'sprite', price: 40, discount: 0, image: 'sprite.jpg'}},
  {category: 'beverages', data: {id: 26, name: 'water', price: 20, discount: 0, image: 'water.jpg'}},
  {category: 'beverages', data: {id: 27, name: 'fresh_juice', price: 50, discount: 0, image: 'fresh_juice.jpg'}},
  {category: 'deserts', data: {id: 28, name: 'cheesecake', price: 80, discount: 0, image: 'cheesecake.jpg'}},
];
export default products;
